name: lint
version: 1.8.1
description: An opinionated, community-driven set of lint rules for Dart and Flutter projects. Like pedantic but stricter
homepage: https://github.com/passsy/dart-lint

environment:
  sdk: '>=2.15.0-7.0.dev <3.0.0'
