name: lint
version: 1.10.0
description: An opinionated, community-driven set of lint rules for Dart and Flutter projects. Like pedantic but stricter
repository: https://github.com/passsy/dart-lint
issue_tracker: https://github.com/passsy/dart-lint/issues

environment:
  sdk: '>=2.17.0 <3.0.0'
