name: lint
version: 1.2.0
description: An opiniated, community-driven set of lint rules for Dart and Flutter projects. Like pedantic but stricter
homepage: https://github.com/passsy/dart-lint

environment:
  sdk: '>=2.8.0-dev.16.0 <3.0.0'
