name: lint
version: 1.3.0-dev.d29.1
description: An opiniated, community-driven set of lint rules for Dart and Flutter projects. Like pedantic but stricter
homepage: https://github.com/passsy/dart-lint

environment:
  sdk: '>=2.9.0-4.0.dev <3.0.0'
